image: gcc

build:
  stage: build
  before_script: 
    - apt update
    - apt install libegl1-mesa-dev libgles2-mesa-dev
    - apt install -y libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev libsdl2-image-dev
    - apt install -y libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-gfx-1.0-0 libsdl2-image-2.0-0
    - mkdir build
    - cd build
    - cmake ..
  script: 
    - make

test:
  stage: test
  script:
    - echo "passed"